name: flutter_playground
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mapbox_maps_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.0
  fl_chart: ^0.62.0
  flutter_slidable: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
